import type {
  AuditLogEntry,
  AuthUser,
  Category,
  CustomerProfile,
  Device,
  Product,
  Quotation,
} from "../types";

export const mockCategories: Category[] = [
  { id: "cat-tshirt", name: "T-Shirts" },
  { id: "cat-tshirt-round", name: "Round Neck", parentId: "cat-tshirt" },
  { id: "cat-tshirt-polo", name: "Polo", parentId: "cat-tshirt" },
  { id: "cat-tshirt-vneck", name: "V-Neck", parentId: "cat-tshirt" },
  { id: "cat-shirt", name: "Shirts" },
  { id: "cat-shirt-formal", name: "Formal", parentId: "cat-shirt" },
  { id: "cat-shirt-casual", name: "Casual", parentId: "cat-shirt" },
];

export const mockProducts: Product[] = [
  {
    id: "p-001",
    sku: "PLO-001",
    name: "Classic Polo T-Shirt",
    categoryId: "cat-tshirt-polo",
    categoryName: "Polo",
    description: "Pique knit polo, reinforced collar, side vents. Built for print and embroidery runs.",
    fabric: "220 GSM Cotton Pique",
    gsm: 220,
    fit: "Regular",
    sleeveType: "Half Sleeve",
    status: "ACTIVE",
    featured: true,
    images: [{ url: "", alt: "Classic Polo T-Shirt", order: 1 }],
    moq: 100,
    basePrice: 250,
    priceTiers: [
      { minQuantity: 1, unitPrice: 250 },
      { minQuantity: 100, unitPrice: 230 },
      { minQuantity: 500, unitPrice: 215 },
      { minQuantity: 1000, unitPrice: 195 },
    ],
    variants: [
      { id: "v-001", sku: "PLO-001-BLK-S", color: "Black", size: "S", moq: 100 },
      { id: "v-002", sku: "PLO-001-BLK-M", color: "Black", size: "M", moq: 100 },
      { id: "v-003", sku: "PLO-001-BLK-L", color: "Black", size: "L", moq: 100 },
      { id: "v-004", sku: "PLO-001-WHT-S", color: "White", size: "S", moq: 100 },
      { id: "v-005", sku: "PLO-001-WHT-M", color: "White", size: "M", moq: 100 },
    ],
  },
  {
    id: "p-002",
    sku: "RND-014",
    name: "Round Neck Basic Tee",
    categoryId: "cat-tshirt-round",
    categoryName: "Round Neck",
    description: "Single jersey round neck, tubular body for a clean print surface.",
    fabric: "180 GSM Combed Cotton",
    gsm: 180,
    fit: "Regular",
    sleeveType: "Half Sleeve",
    status: "ACTIVE",
    featured: true,
    images: [{ url: "", alt: "Round Neck Basic Tee", order: 1 }],
    moq: 150,
    basePrice: 165,
    priceTiers: [
      { minQuantity: 1, unitPrice: 165 },
      { minQuantity: 150, unitPrice: 150 },
      { minQuantity: 500, unitPrice: 138 },
      { minQuantity: 1000, unitPrice: 125 },
    ],
    variants: [
      { id: "v-006", sku: "RND-014-NVY-M", color: "Navy", size: "M", moq: 150 },
      { id: "v-007", sku: "RND-014-NVY-L", color: "Navy", size: "L", moq: 150 },
      { id: "v-008", sku: "RND-014-GRY-M", color: "Grey Melange", size: "M", moq: 150 },
    ],
  },
  {
    id: "p-003",
    sku: "SHF-220",
    name: "Formal Full Sleeve Shirt",
    categoryId: "cat-shirt-formal",
    categoryName: "Formal",
    description: "Poplin weave, spread collar, single-needle stitch finish for corporate uniform orders.",
    fabric: "120 GSM Cotton Poplin",
    gsm: 120,
    fit: "Slim",
    sleeveType: "Full Sleeve",
    status: "ACTIVE",
    featured: false,
    images: [{ url: "", alt: "Formal Full Sleeve Shirt", order: 1 }],
    moq: 50,
    basePrice: 420,
    priceTiers: [
      { minQuantity: 1, unitPrice: 420 },
      { minQuantity: 50, unitPrice: 395 },
      { minQuantity: 200, unitPrice: 370 },
    ],
    variants: [
      { id: "v-009", sku: "SHF-220-WHT-M", color: "White", size: "M", moq: 50 },
      { id: "v-010", sku: "SHF-220-SKY-L", color: "Sky Blue", size: "L", moq: 50 },
    ],
  },
];

export const mockCustomers: CustomerProfile[] = [
  {
    id: "cust-001",
    firstName: "Anita",
    lastName: "Sharma",
    email: "anita@abcgarments.in",
    mobileNumber: "+91 98200 11223",
    companyName: "ABC Garments Pvt Ltd",
    businessType: "Retailer",
    gstin: "07ABCDE1234F1Z5",
    address: { line1: "12 Textile Market", city: "Surat", state: "Gujarat", country: "India", postalCode: "395002" },
    status: "PENDING",
    createdAt: "2026-08-08T10:15:00Z",
  },
  {
    id: "cust-002",
    firstName: "Rajeev",
    lastName: "Menon",
    email: "rajeev@southernthreads.in",
    mobileNumber: "+91 98450 66210",
    companyName: "Southern Threads Co.",
    businessType: "Distributor",
    address: { line1: "44 Mill Road", city: "Coimbatore", state: "Tamil Nadu", country: "India", postalCode: "641001" },
    status: "APPROVED",
    createdAt: "2026-07-20T09:00:00Z",
  },
];

export const mockDevices: Device[] = [
  {
    id: "dev-001",
    userId: "cust-002",
    fingerprint: "fp_9a21b",
    ipAddress: "103.21.4.11",
    userAgent: "Chrome 127 / Windows 11",
    browser: "Chrome",
    os: "Windows 11",
    createdAt: "2026-07-20T09:05:00Z",
    approvedAt: "2026-07-20T11:00:00Z",
    lastLogin: "2026-08-10T08:12:00Z",
    status: "APPROVED",
  },
  {
    id: "dev-002",
    userId: "cust-002",
    fingerprint: "fp_77cd1",
    ipAddress: "49.36.88.4",
    userAgent: "Safari 17 / iPhone",
    browser: "Safari",
    os: "iOS 17",
    createdAt: "2026-08-09T14:30:00Z",
    status: "PENDING",
  },
];

export const mockQuotations: Quotation[] = [
  {
    id: "q-001",
    quotationNumber: "QT-2026-000041",
    customerId: "cust-002",
    customerName: "Southern Threads Co.",
    items: [
      {
        productId: "p-001",
        variantId: "v-001",
        productName: "Classic Polo T-Shirt",
        sku: "PLO-001-BLK-S",
        color: "Black",
        size: "S",
        quantity: 500,
        unitPrice: 215,
        lineTotal: 107500,
      },
    ],
    subtotal: 107500,
    tax: 0,
    grandTotal: 107500,
    status: "SUBMITTED",
    createdAt: "2026-08-10T06:40:00Z",
    validUntil: "2026-08-24T00:00:00Z",
  },
];

export const mockAuditLog: AuditLogEntry[] = [
  {
    id: "aud-001",
    user: "admin@kkkgarments.in",
    action: "APPROVED_CUSTOMER",
    entity: "Customer",
    entityId: "cust-002",
    newValue: "APPROVED",
    ip: "203.0.113.10",
    timestamp: "2026-07-20T11:00:00Z",
  },
  {
    id: "aud-002",
    user: "admin@kkkgarments.in",
    action: "CHANGED_PRICE",
    entity: "Product",
    entityId: "p-001",
    oldValue: "₹240",
    newValue: "₹230",
    ip: "203.0.113.10",
    timestamp: "2026-08-01T09:20:00Z",
  },
];

export const mockCurrentCustomer: AuthUser = {
  id: "cust-002",
  name: "Rajeev Menon",
  email: "rajeev@southernthreads.in",
  role: "CUSTOMER",
  status: "APPROVED",
};

export const mockCurrentAdmin: AuthUser = {
  id: "admin-001",
  name: "Kavita Rao",
  email: "admin@kkkgarments.in",
  role: "ADMIN",
  status: "APPROVED",
};
